sudo: required
services:
  - docker
install:
  - docker pull sangerpathogens/bio-tradis
script:
  - docker run --rm -it sangerpathogens/bio-tradis /bin/bash -c "git clone https://github.com/telatin/Bio-Tradis.git && cd Bio-Tradis && source ./install_dependencies.sh && dzil test"


